import type { Metadata } from "next";
import "./globals.css"
import { DarkThemeProvider } from "../contexts/DarkThemeContext";
import ThemeInitializer from "../components/ThemeInitializer";
import ScrollTop from "../components/ScrollTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DarkThemeProvider>
      <html lang="en" className="">
        <body className="dark:bg-darkTheme dark:text-white">
          <ThemeInitializer />
          <ScrollTop />
          {children}
        </body>
      </html>
    </DarkThemeProvider>
  );
}
